module.exports = [
  {
    name: 'User',
    modelName: 'user',
    idType: 'string',
    optionField: 'name',
    searchFields: ['name', 'email'],
    defaultOrderBy: { createdAt: 'desc' },
    relations: [],
  },
  {
    name: 'Blog',
    modelName: 'blog',
    idType: 'number',
    optionField: 'title',
    searchFields: ['title', 'slug', 'content'],
    defaultOrderBy: { createdAt: 'desc' },
    relations: [
      {
        name: 'author',
        type: 'many-to-one',
        model: 'user',
        field: 'authorId',
      },
      {
        name: 'categories',
        type: 'many-to-many',
        model: 'category',
        joinTable: 'blogCategory',
        foreignKey: 'categoryId',
      },
    ],
  },
  {
    name: 'Category',
    modelName: 'category',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'description'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'blogs',
        type: 'many-to-many',
        model: 'blog',
        joinTable: 'blogCategory',
        foreignKey: 'blogId',
      },
    ],
  },
  {
    name: 'ContactSubmission',
    modelName: 'contactSubmission',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'email', 'message'],
    defaultOrderBy: { createdAt: 'desc' },
    relations: [],
  },
  // Running Events Models
  {
    name: 'Region',
    modelName: 'region',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'code'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [],
  },
  {
    name: 'District',
    modelName: 'district',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'code'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'region',
        type: 'many-to-one',
        model: 'region',
        field: 'regionId',
      },
    ],
  },
  {
    name: 'Location',
    modelName: 'location',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'city', 'street'],
    defaultOrderBy: { name: 'asc' },
    relations: [
      {
        name: 'district',
        type: 'many-to-one',
        model: 'district',
        field: 'districtId',
      },
      {
        name: 'region',
        type: 'many-to-one',
        model: 'region',
        field: 'regionId',
      },
    ],
  },
  {
    name: 'Organizer',
    modelName: 'organizer',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'email'],
    defaultOrderBy: { name: 'asc' },
    relations: [],
  },
  {
    name: 'Event',
    modelName: 'event',
    idType: 'number',
    optionField: 'title',
    searchFields: ['title', 'slug', 'description'],
    defaultOrderBy: { startDate: 'desc' },
    relations: [
      {
        name: 'location',
        type: 'many-to-one',
        model: 'location',
        field: 'locationId',
      },
      {
        name: 'organizer',
        type: 'many-to-one',
        model: 'organizer',
        field: 'organizerId',
      },
    ],
  },
  {
    name: 'Run',
    modelName: 'run',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'event',
        type: 'many-to-one',
        model: 'event',
        field: 'eventId',
      },
      {
        name: 'categories',
        type: 'many-to-many',
        model: 'runCategory',
        joinTable: 'runCategoryAssignment',
        foreignKey: 'categoryId',
      },
    ],
  },
  {
    name: 'RunCategory',
    modelName: 'runCategory',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'code'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'runs',
        type: 'many-to-many',
        model: 'run',
        joinTable: 'runCategoryAssignment',
        foreignKey: 'runId',
      },
    ],
  },
  {
    name: 'RunEntryFee',
    modelName: 'runEntryFee',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'run',
        type: 'many-to-one',
        model: 'run',
        field: 'runId',
      },
    ],
  },
  {
    name: 'EventSchedule',
    modelName: 'eventSchedule',
    idType: 'number',
    optionField: 'title',
    searchFields: ['title', 'description'],
    defaultOrderBy: { startTime: 'asc' },
    relations: [
      {
        name: 'event',
        type: 'many-to-one',
        model: 'event',
        field: 'eventId',
      },
    ],
  },
  {
    name: 'Partner',
    modelName: 'partner',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'description'],
    defaultOrderBy: { name: 'asc' },
    relations: [
      {
        name: 'events',
        type: 'many-to-many',
        model: 'event',
        joinTable: 'eventPartner',
        foreignKey: 'eventId',
      },
    ],
  },
  {
    name: 'EventAttachment',
    modelName: 'eventAttachment',
    idType: 'number',
    optionField: 'title',
    searchFields: ['title', 'description'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'event',
        type: 'many-to-one',
        model: 'event',
        field: 'eventId',
      },
    ],
  },
  {
    name: 'Registration',
    modelName: 'registration',
    idType: 'number',
    optionField: 'registrationNumber',
    searchFields: ['registrationNumber', 'firstName', 'lastName', 'email'],
    defaultOrderBy: { registeredAt: 'desc' },
    relations: [
      {
        name: 'run',
        type: 'many-to-one',
        model: 'run',
        field: 'runId',
      },
      {
        name: 'category',
        type: 'many-to-one',
        model: 'runCategory',
        field: 'categoryId',
      },
    ],
  },
  {
    name: 'RunResult',
    modelName: 'runResult',
    idType: 'number',
    optionField: 'id',
    searchFields: ['firstName', 'lastName', 'club'],
    defaultOrderBy: { overallPlace: 'asc' },
    relations: [
      {
        name: 'run',
        type: 'many-to-one',
        model: 'run',
        field: 'runId',
      },
    ],
  },
]
