module.exports = [
  {
    name: 'User',
    modelName: 'user',
    idType: 'string',
    optionField: 'name',
    searchFields: ['name', 'email'],
    defaultOrderBy: { createdAt: 'desc' },
    relations: [],
  },
  {
    name: 'Blog',
    modelName: 'blog',
    idType: 'number',
    optionField: 'title',
    searchFields: ['title', 'slug', 'content'],
    defaultOrderBy: { createdAt: 'desc' },
    relations: [
      {
        name: 'author',
        type: 'many-to-one',
        model: 'user',
        field: 'authorId',
      },
      {
        name: 'categories',
        type: 'many-to-many',
        model: 'category',
        joinTable: 'blogCategory',
        foreignKey: 'categoryId',
      },
    ],
  },
  {
    name: 'Category',
    modelName: 'category',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'description'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'blogs',
        type: 'many-to-many',
        model: 'blog',
        joinTable: 'blogCategory',
        foreignKey: 'blogId',
      },
    ],
  },
  {
    name: 'Gallery',
    modelName: 'gallery',
    idType: 'number',
    optionField: 'title',
    searchFields: ['title', 'description'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [],
  },
  {
    name: 'GalleryImage',
    modelName: 'galleryImage',
    idType: 'number',
    optionField: 'title',
    searchFields: ['title', 'description'],
    defaultOrderBy: { sortOrder: 'asc' },
    relations: [
      {
        name: 'gallery',
        type: 'many-to-one',
        model: 'gallery',
        field: 'galleryId',
      },
    ],
  },
  {
    name: 'ContactSubmission',
    modelName: 'contactSubmission',
    idType: 'number',
    optionField: 'name',
    searchFields: ['name', 'email', 'message'],
    defaultOrderBy: { createdAt: 'desc' },
    relations: [],
  },
]
