import { ModelConfig } from '@/lib/admin/types'
import { FileText } from 'lucide-react'

export const blogConfig: ModelConfig = {
  name: 'Blog',
  namePlural: 'Blogs',
  nameSingular: 'Blog',
  icon: FileText,
  description: 'Manage blog posts',
  primaryField: 'title',

  defaultSort: { field: 'createdAt', direction: 'desc' },
  searchFields: ['title', 'slug', 'content'],
  perPage: 15,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'author',
      type: 'relation',
      label: 'Author',
      required: true,
      showInList: true,
      relation: {
        model: 'User',
        displayField: 'name',
        foreignKey: 'authorId',
        idType: 'string',
      },
    },
    {
      name: 'title',
      type: 'string',
      label: 'Title',
      required: true,
      placeholder: 'Enter blog post title',
      min: 5,
      max: 200,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'slug',
      type: 'string',
      label: 'Slug',
      required: true,
      placeholder: 'url-friendly-slug',
      helpText: 'URL-friendly version of the title',
      pattern: /^[a-z0-9-]+$/,
      showInList: true,
      searchable: true,
    },
    {
      name: 'content',
      type: 'text',
      label: 'Content',
      required: true,
      placeholder: 'Write your blog post content here...',
      min: 10,
      showInList: false,
      searchable: true,
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Published', value: 'published' },
        { label: 'Archived', value: 'archived' },
      ],
      showInList: true,
      sortable: true,
    },
    {
      name: 'categories',
      type: 'relation-many',
      label: 'Categories',
      showInList: true,
      relation: {
        model: 'Category',
        displayField: 'name',
        joinTable: 'BlogCategory',
        localKey: 'blogId',
        foreignKeyRef: 'categoryId',
      },
    },
    {
      name: 'views',
      type: 'number',
      label: 'Views',
      defaultValue: 0,
      min: 0,
      readonly: true,
      showInList: true,
      sortable: true,
    },
    {
      name: 'publishedAt',
      type: 'date',
      label: 'Published At',
      helpText: 'When the blog post was published',
      showInList: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
      sortable: true,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
}
