import { ModelConfig } from '@/lib/admin/types';
import { Calendar } from 'lucide-react';

export const eventConfig: ModelConfig = {
  name: 'Event',
  namePlural: 'Events',
  nameSingular: 'Event',
  icon: Calendar,
  description: 'Manage running events',
  primaryField: 'title',

  defaultSort: { field: 'startDate', direction: 'desc' },
  searchFields: ['title', 'slug', 'description'],
  perPage: 20,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'title',
      type: 'string',
      label: 'Event Title',
      required: true,
      placeholder: 'Bratislava Marathon 2025',
      min: 3,
      max: 200,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'slug',
      type: 'string',
      label: 'Slug',
      required: true,
      placeholder: 'bratislava-marathon-2025',
      min: 3,
      max: 200,
      helpText: 'URL-friendly identifier',
      showInList: false,
      searchable: true,
    },
    {
      name: 'description',
      type: 'text',
      label: 'Short Description',
      placeholder: 'Brief description for listings...',
      max: 500,
      showInList: false,
      searchable: true,
    },
    {
      name: 'longDescription',
      type: 'text',
      label: 'Full Description',
      placeholder: 'Detailed event description...',
      max: 5000,
      helpText: 'Full event details',
      showInList: false,
    },
    {
      name: 'startDate',
      type: 'date',
      label: 'Start Date',
      required: true,
      showInList: true,
      sortable: true,
    },
    {
      name: 'endDate',
      type: 'date',
      label: 'End Date',
      required: true,
      showInList: true,
      sortable: true,
    },
    {
      name: 'locationId',
      type: 'relation',
      label: 'Location',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Location',
        displayField: 'name',
        foreignKey: 'locationId',
        idType: 'number',
      },
    },
    {
      name: 'organizerId',
      type: 'relation',
      label: 'Organizer',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Organizer',
        displayField: 'name',
        foreignKey: 'organizerId',
        idType: 'number',
      },
    },
    {
      name: 'contactEmail',
      type: 'string',
      label: 'Contact Email',
      placeholder: 'info@event.sk',
      max: 100,
      showInList: false,
    },
    {
      name: 'contactPhone',
      type: 'string',
      label: 'Contact Phone',
      placeholder: '+421 900 123 456',
      max: 20,
      showInList: false,
    },
    {
      name: 'bankAccount',
      type: 'string',
      label: 'Bank Account (IBAN)',
      placeholder: 'SK31 1200 0000 1987 4263 7541',
      max: 50,
      helpText: 'IBAN for entry fee payments',
      showInList: false,
    },
    {
      name: 'paymentNote',
      type: 'text',
      label: 'Payment Note',
      placeholder: 'Payment instructions...',
      max: 1000,
      helpText: 'Instructions for participants on how to pay',
      showInList: false,
    },
    {
      name: 'coverImage',
      type: 'string',
      label: 'Cover Image',
      placeholder: '/uploads/events/cover.jpg',
      max: 500,
      helpText: 'Path or URL to cover image',
      showInList: false,
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      required: true,
      defaultValue: 'draft',
      showInList: true,
      sortable: true,
      options: [
        { value: 'draft', label: 'Draft' },
        { value: 'published', label: 'Published' },
        { value: 'cancelled', label: 'Cancelled' },
        { value: 'completed', label: 'Completed' },
      ],
    },
    {
      name: 'registrationOpenDate',
      type: 'date',
      label: 'Registration Opens',
      helpText: 'When registration becomes available',
      showInList: false,
    },
    {
      name: 'registrationCloseDate',
      type: 'date',
      label: 'Registration Closes',
      helpText: 'Last day to register',
      showInList: false,
    },
    {
      name: 'maxParticipants',
      type: 'number',
      label: 'Max Participants',
      placeholder: '5000',
      helpText: 'Maximum number of participants (optional)',
      showInList: false,
    },
    {
      name: 'rules',
      type: 'text',
      label: 'Rules',
      placeholder: 'Event rules and regulations...',
      max: 5000,
      helpText: 'Competition rules and requirements',
      showInList: false,
    },
    {
      name: 'galleries',
      type: 'relation-many',
      label: 'Galleries',
      showInList: false,
      relation: {
        model: 'Gallery',
        displayField: 'title',
        joinTable: 'eventGallery',
        localKey: 'eventId',
        foreignKeyRef: 'galleryId',
        idType: 'number',
      },
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
