import { ModelConfig } from '@/lib/admin/types';
import { Paperclip } from 'lucide-react';

export const eventAttachmentConfig: ModelConfig = {
  name: 'EventAttachment',
  namePlural: 'Event Attachments',
  nameSingular: 'Event Attachment',
  icon: Paperclip,
  description: 'Manage event files and attachments',
  primaryField: 'title',
  group: 'Events',

  defaultSort: { field: 'sortOrder', direction: 'asc' },
  searchFields: ['title', 'description'],
  perPage: 50,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'eventId',
      type: 'relation',
      label: 'Event',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Event',
        displayField: 'title',
        foreignKey: 'eventId',
        idType: 'number',
      },
    },
    {
      name: 'title',
      type: 'string',
      label: 'Title',
      required: true,
      placeholder: 'Race Regulations',
      min: 2,
      max: 200,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'fileUrl',
      type: 'string',
      label: 'File URL',
      required: true,
      placeholder: '/uploads/attachments/regulations.pdf',
      max: 500,
      helpText: 'Path or URL to the file',
      showInList: true,
    },
    {
      name: 'fileType',
      type: 'select',
      label: 'File Type',
      showInList: true,
      options: [
        { value: 'pdf', label: 'PDF' },
        { value: 'image', label: 'Image' },
        { value: 'doc', label: 'Document' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      name: 'fileSize',
      type: 'number',
      label: 'File Size (bytes)',
      placeholder: '1024000',
      helpText: 'File size in bytes',
      showInList: false,
    },
    {
      name: 'description',
      type: 'text',
      label: 'Description',
      placeholder: 'Brief description...',
      max: 500,
      showInList: false,
      searchable: true,
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      helpText: 'Display order',
      showInList: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
