import { ModelConfig } from '@/lib/admin/types';
import { Clock } from 'lucide-react';

export const eventScheduleConfig: ModelConfig = {
  name: 'EventSchedule',
  namePlural: 'Event Schedule',
  nameSingular: 'Schedule Item',
  icon: Clock,
  description: 'Manage event schedule and activities',
  primaryField: 'title',

  defaultSort: { field: 'startTime', direction: 'asc' },
  searchFields: ['title', 'description'],
  perPage: 50,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'eventId',
      type: 'relation',
      label: 'Event',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Event',
        displayField: 'title',
        foreignKey: 'eventId',
        idType: 'number',
      },
    },
    {
      name: 'title',
      type: 'string',
      label: 'Title',
      required: true,
      placeholder: 'Registration Opens',
      min: 2,
      max: 200,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'description',
      type: 'text',
      label: 'Description',
      placeholder: 'Additional details...',
      max: 1000,
      showInList: false,
      searchable: true,
    },
    {
      name: 'startTime',
      type: 'date',
      label: 'Start Time',
      required: true,
      showInList: true,
      sortable: true,
    },
    {
      name: 'endTime',
      type: 'date',
      label: 'End Time',
      helpText: 'Optional end time for the activity',
      showInList: true,
      sortable: true,
    },
    {
      name: 'location',
      type: 'string',
      label: 'Location',
      placeholder: 'Main Pavilion',
      max: 200,
      helpText: 'Specific location within the event',
      showInList: true,
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      helpText: 'Display order',
      showInList: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
