import { ModelConfig } from '@/lib/admin/types'
import { Images } from 'lucide-react'

export const galleryConfig: ModelConfig = {
  name: 'Gallery',
  namePlural: 'Galleries',
  nameSingular: 'Gallery',
  icon: Images,
  description: 'Manage photo galleries',
  primaryField: 'title',

  defaultSort: { field: 'sortOrder', direction: 'asc' },
  searchFields: ['title', 'description'],
  perPage: 15,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'title',
      type: 'string',
      label: 'Gallery Title',
      required: true,
      placeholder: 'Summer Vacation 2025',
      min: 3,
      max: 200,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'slug',
      type: 'string',
      label: 'Slug',
      required: true,
      placeholder: 'summer-vacation-2025',
      helpText: 'URL-friendly identifier',
      pattern: /^[a-z0-9-]+$/,
      showInList: true,
      searchable: true,
    },
    {
      name: 'description',
      type: 'text',
      label: 'Description',
      placeholder: 'Describe this gallery...',
      max: 1000,
      showInList: false,
      searchable: true,
    },
    {
      name: 'coverImage',
      type: 'string',
      label: 'Cover Image URL',
      placeholder: '/images/galleries/cover.jpg',
      helpText: 'Optional featured image URL',
      showInList: false,
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Published', value: 'published' },
        { label: 'Archived', value: 'archived' },
      ],
      showInList: true,
      sortable: true,
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      helpText: 'Order in gallery listing',
      showInList: true,
      sortable: true,
    },
    {
      name: 'publishedAt',
      type: 'date',
      label: 'Published At',
      showInList: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
      sortable: true,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
}
