import { ModelConfig } from '@/lib/admin/types';
import { MapPin } from 'lucide-react';

export const locationConfig: ModelConfig = {
  name: 'Location',
  namePlural: 'Locations',
  nameSingular: 'Location',
  icon: MapPin,
  description: 'Manage event locations',
  primaryField: 'name',

  defaultSort: { field: 'name', direction: 'asc' },
  searchFields: ['name', 'city', 'street'],
  perPage: 20,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'name',
      type: 'string',
      label: 'Location Name',
      required: true,
      placeholder: 'Petržalka Sports Complex',
      min: 2,
      max: 200,
      helpText: 'User-friendly name for the location',
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'street',
      type: 'string',
      label: 'Street',
      placeholder: 'Junácka 4',
      max: 200,
      showInList: false,
    },
    {
      name: 'city',
      type: 'string',
      label: 'City',
      required: true,
      placeholder: 'Bratislava',
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'postalCode',
      type: 'string',
      label: 'Postal Code',
      placeholder: '85101',
      max: 10,
      showInList: false,
    },
    {
      name: 'districtId',
      type: 'relation',
      label: 'District',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'District',
        displayField: 'name',
        foreignKey: 'districtId',
        idType: 'number',
      },
    },
    {
      name: 'regionId',
      type: 'relation',
      label: 'Region',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Region',
        displayField: 'name',
        foreignKey: 'regionId',
        idType: 'number',
      },
    },
    {
      name: 'gpsLatitude',
      type: 'number',
      label: 'GPS Latitude',
      placeholder: '48.1351',
      helpText: 'Optional GPS latitude for mapping',
      showInList: false,
    },
    {
      name: 'gpsLongitude',
      type: 'number',
      label: 'GPS Longitude',
      placeholder: '17.0887',
      helpText: 'Optional GPS longitude for mapping',
      showInList: false,
    },
    {
      name: 'locationNote',
      type: 'text',
      label: 'Location Note',
      placeholder: 'Near the main entrance, city park area',
      max: 500,
      helpText: 'Optional informal description of the location',
      showInList: false,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
