import { ModelConfig } from '@/lib/admin/types';
import { Users } from 'lucide-react';

export const organizerConfig: ModelConfig = {
  name: 'Organizer',
  namePlural: 'Organizers',
  nameSingular: 'Organizer',
  icon: Users,
  description: 'Manage event organizers',
  primaryField: 'name',
  group: 'Events',

  defaultSort: { field: 'name', direction: 'asc' },
  searchFields: ['name', 'email'],
  perPage: 20,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'name',
      type: 'string',
      label: 'Organizer Name',
      required: true,
      placeholder: 'Bratislava Running Club',
      min: 2,
      max: 200,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'description',
      type: 'text',
      label: 'Description',
      placeholder: 'Brief description of the organizer...',
      max: 1000,
      showInList: false,
    },
    {
      name: 'email',
      type: 'string',
      label: 'Email',
      placeholder: 'contact@organizer.sk',
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'phone',
      type: 'string',
      label: 'Phone',
      placeholder: '+421 900 123 456',
      max: 20,
      showInList: true,
    },
    {
      name: 'website',
      type: 'string',
      label: 'Website',
      placeholder: 'https://organizer.sk',
      max: 200,
      showInList: false,
    },
    {
      name: 'logo',
      type: 'string',
      label: 'Logo URL',
      placeholder: '/uploads/organizers/logo.png',
      max: 500,
      helpText: 'Path or URL to organizer logo',
      showInList: false,
    },
    {
      name: 'isActive',
      type: 'boolean',
      label: 'Active',
      defaultValue: true,
      helpText: 'Whether the organizer is currently active',
      showInList: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
