import { ModelConfig } from '@/lib/admin/types';
import { UserPlus } from 'lucide-react';

export const registrationConfig: ModelConfig = {
  name: 'Registration',
  namePlural: 'Registrations',
  nameSingular: 'Registration',
  icon: UserPlus,
  description: 'Manage race registrations',
  primaryField: 'registrationNumber',

  defaultSort: { field: 'registeredAt', direction: 'desc' },
  searchFields: ['registrationNumber', 'guestFirstName', 'guestLastName', 'guestEmail'],
  perPage: 50,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'registrationNumber',
      type: 'string',
      label: 'Registration Number',
      required: true,
      placeholder: 'BRM2025-000001',
      max: 50,
      helpText: 'Unique registration number',
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'runId',
      type: 'relation',
      label: 'Run',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Run',
        displayField: 'name',
        foreignKey: 'runId',
        idType: 'number',
      },
    },
    {
      name: 'categoryId',
      type: 'relation',
      label: 'Category',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'RunCategory',
        displayField: 'name',
        foreignKey: 'categoryId',
        idType: 'number',
      },
    },
    {
      name: 'runnerId',
      type: 'relation',
      label: 'Runner Account',
      helpText: 'Optional link to runner profile',
      showInList: false,
      relation: {
        model: 'Runner',
        displayField: 'email',
        foreignKey: 'runnerId',
        idType: 'string',
      },
    },
    {
      name: 'guestFirstName',
      type: 'string',
      label: 'First Name',
      required: true,
      placeholder: 'Ján',
      min: 2,
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'guestLastName',
      type: 'string',
      label: 'Last Name',
      required: true,
      placeholder: 'Novák',
      min: 2,
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'guestEmail',
      type: 'string',
      label: 'Email',
      required: true,
      placeholder: 'runner@example.sk',
      max: 100,
      showInList: true,
      searchable: true,
    },
    {
      name: 'guestPhone',
      type: 'string',
      label: 'Phone',
      placeholder: '+421 901 234 567',
      max: 20,
      showInList: false,
    },
    {
      name: 'guestDateOfBirth',
      type: 'date',
      label: 'Date of Birth',
      required: true,
      showInList: false,
    },
    {
      name: 'guestGender',
      type: 'select',
      label: 'Gender',
      required: true,
      showInList: false,
      options: [
        { value: 'male', label: 'Male' },
        { value: 'female', label: 'Female' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      name: 'guestCity',
      type: 'string',
      label: 'City',
      placeholder: 'Bratislava',
      max: 100,
      showInList: false,
    },
    {
      name: 'guestClub',
      type: 'string',
      label: 'Running Club',
      placeholder: 'Bratislava Running Club',
      max: 200,
      showInList: false,
    },
    {
      name: 'registeredAt',
      type: 'date',
      label: 'Registered At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
      sortable: true,
    },
    {
      name: 'paid',
      type: 'boolean',
      label: 'Paid',
      defaultValue: false,
      showInList: true,
      sortable: true,
    },
    {
      name: 'paidAmount',
      type: 'number',
      label: 'Paid Amount',
      placeholder: '40.00',
      helpText: 'Amount paid in EUR',
      showInList: false,
    },
    {
      name: 'paidAt',
      type: 'date',
      label: 'Paid At',
      helpText: 'When payment was received',
      showInList: false,
    },
    {
      name: 'paymentNote',
      type: 'text',
      label: 'Payment Note',
      placeholder: 'Payment reference...',
      max: 500,
      showInList: false,
    },
    {
      name: 'presented',
      type: 'boolean',
      label: 'Presented',
      defaultValue: false,
      helpText: 'Did the runner show up?',
      showInList: true,
      sortable: true,
    },
    {
      name: 'bibNumber',
      type: 'string',
      label: 'Bib Number',
      placeholder: '501',
      max: 20,
      helpText: 'Race bib number assigned',
      showInList: true,
      sortable: true,
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      required: true,
      defaultValue: 'pending',
      showInList: true,
      sortable: true,
      options: [
        { value: 'pending', label: 'Pending' },
        { value: 'confirmed', label: 'Confirmed' },
        { value: 'cancelled', label: 'Cancelled' },
      ],
    },
    {
      name: 'notes',
      type: 'text',
      label: 'Notes',
      placeholder: 'Internal notes...',
      max: 1000,
      helpText: 'Admin notes',
      showInList: false,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
