import { ModelConfig } from '@/lib/admin/types';
import { Flag } from 'lucide-react';

export const runConfig: ModelConfig = {
  name: 'Run',
  namePlural: 'Runs',
  nameSingular: 'Run',
  icon: Flag,
  description: 'Manage individual races within events',
  primaryField: 'name',

  defaultSort: { field: 'sortOrder', direction: 'asc' },
  searchFields: ['name'],
  perPage: 20,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'eventId',
      type: 'relation',
      label: 'Event',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Event',
        displayField: 'title',
        foreignKey: 'eventId',
        idType: 'number',
      },
    },
    {
      name: 'name',
      type: 'string',
      label: 'Run Name',
      required: true,
      placeholder: 'Marathon',
      min: 2,
      max: 100,
      helpText: 'Name of the race (e.g., Marathon, 10K)',
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'distance',
      type: 'number',
      label: 'Distance (km)',
      required: true,
      placeholder: '42.195',
      helpText: 'Distance in kilometers',
      showInList: true,
      sortable: true,
    },
    {
      name: 'elevationGain',
      type: 'number',
      label: 'Elevation Gain (m)',
      placeholder: '120',
      helpText: 'Total elevation gain in meters',
      showInList: false,
    },
    {
      name: 'surface',
      type: 'select',
      label: 'Surface',
      showInList: true,
      options: [
        { value: 'asphalt', label: 'Asphalt' },
        { value: 'trail', label: 'Trail' },
        { value: 'mixed', label: 'Mixed' },
        { value: 'gravel', label: 'Gravel' },
      ],
    },
    {
      name: 'startTime',
      type: 'date',
      label: 'Start Time',
      required: true,
      helpText: 'When this race starts',
      showInList: true,
      sortable: true,
    },
    {
      name: 'maxParticipants',
      type: 'number',
      label: 'Max Participants',
      placeholder: '2000',
      helpText: 'Maximum number of participants for this run',
      showInList: false,
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      helpText: 'Display order within event',
      showInList: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
