import { ModelConfig } from '@/lib/admin/types';
import { Users } from 'lucide-react';

export const runCategoryConfig: ModelConfig = {
  name: 'RunCategory',
  namePlural: 'Run Categories',
  nameSingular: 'Run Category',
  icon: Users,
  description: 'Manage age/gender categories for runs',
  primaryField: 'name',
  group: 'Runs',

  defaultSort: { field: 'sortOrder', direction: 'asc' },
  searchFields: ['name', 'code'],
  perPage: 50,

  filters: [],

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'name',
      type: 'string',
      label: 'Category Name',
      required: true,
      placeholder: 'Men 40-49',
      min: 2,
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'code',
      type: 'string',
      label: 'Code',
      required: true,
      placeholder: 'M40',
      min: 1,
      max: 20,
      helpText: 'Short code for the category',
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'minAge',
      type: 'number',
      label: 'Minimum Age',
      placeholder: '40',
      helpText: 'Minimum age for this category (optional)',
      showInList: true,
    },
    {
      name: 'maxAge',
      type: 'number',
      label: 'Maximum Age',
      placeholder: '49',
      helpText: 'Maximum age for this category (optional)',
      showInList: true,
    },
    {
      name: 'gender',
      type: 'select',
      label: 'Gender',
      helpText: 'Select gender or leave as open/mixed',
      showInList: true,
      options: [
        { value: 'mixed', label: 'Open/Mixed' },
        { value: 'male', label: 'Male' },
        { value: 'female', label: 'Female' },
      ],
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      helpText: 'Display order',
      showInList: true,
      sortable: true,
    },
    {
      name: 'runs',
      type: 'relation-many',
      label: 'Assigned Runs',
      showInList: false,
      relation: {
        model: 'Run',
        displayField: 'name',
        joinTable: 'RunCategoryAssignment',
        localKey: 'categoryId',
        foreignKeyRef: 'runId',
      },
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
