import { ModelConfig } from '@/lib/admin/types';
import { Euro } from 'lucide-react';

export const runEntryFeeConfig: ModelConfig = {
  name: 'RunEntryFee',
  namePlural: 'Run Entry Fees',
  nameSingular: 'Run Entry Fee',
  icon: Euro,
  description: 'Manage entry fee pricing tiers',
  primaryField: 'name',

  defaultSort: { field: 'sortOrder', direction: 'asc' },
  searchFields: ['name'],
  perPage: 50,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'runId',
      type: 'relation',
      label: 'Run',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Run',
        displayField: 'name',
        foreignKey: 'runId',
        idType: 'number',
      },
    },
    {
      name: 'name',
      type: 'string',
      label: 'Fee Name',
      required: true,
      placeholder: 'Early Bird',
      min: 2,
      max: 100,
      helpText: 'Name for this pricing tier',
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'amount',
      type: 'number',
      label: 'Amount',
      required: true,
      placeholder: '40.00',
      helpText: 'Fee amount',
      showInList: true,
      sortable: true,
    },
    {
      name: 'currency',
      type: 'string',
      label: 'Currency',
      required: true,
      defaultValue: 'EUR',
      placeholder: 'EUR',
      max: 3,
      showInList: true,
    },
    {
      name: 'validFrom',
      type: 'date',
      label: 'Valid From',
      required: true,
      helpText: 'When this pricing tier becomes active',
      showInList: true,
      sortable: true,
    },
    {
      name: 'validTo',
      type: 'date',
      label: 'Valid To',
      required: true,
      helpText: 'When this pricing tier expires',
      showInList: true,
      sortable: true,
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      helpText: 'Display order',
      showInList: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
