import { ModelConfig } from '@/lib/admin/types';
import { User } from 'lucide-react';

export const runnerConfig: ModelConfig = {
  name: 'Runner',
  namePlural: 'Runners',
  nameSingular: 'Runner',
  icon: User,
  description: 'Manage runner profiles',
  primaryField: 'firstName',

  defaultSort: { field: 'createdAt', direction: 'desc' },
  searchFields: ['firstName', 'lastName', 'email', 'club'],
  perPage: 50,

  fields: [
    {
      name: 'id',
      type: 'string',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'email',
      type: 'string',
      label: 'Email',
      required: true,
      placeholder: 'runner@example.sk',
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'userId',
      type: 'relation',
      label: 'User Account',
      helpText: 'Optional link to user account',
      showInList: false,
      relation: {
        model: 'User',
        displayField: 'name',
        foreignKey: 'userId',
        idType: 'string',
      },
    },
    {
      name: 'firstName',
      type: 'string',
      label: 'First Name',
      required: true,
      placeholder: 'Ján',
      min: 2,
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'lastName',
      type: 'string',
      label: 'Last Name',
      required: true,
      placeholder: 'Novák',
      min: 2,
      max: 100,
      showInList: true,
      sortable: true,
      searchable: true,
    },
    {
      name: 'dateOfBirth',
      type: 'date',
      label: 'Date of Birth',
      required: true,
      showInList: true,
      sortable: true,
    },
    {
      name: 'gender',
      type: 'select',
      label: 'Gender',
      required: true,
      showInList: true,
      sortable: true,
      options: [
        { value: 'male', label: 'Male' },
        { value: 'female', label: 'Female' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      name: 'phone',
      type: 'string',
      label: 'Phone',
      placeholder: '+421 901 234 567',
      max: 20,
      showInList: false,
    },
    {
      name: 'city',
      type: 'string',
      label: 'City',
      placeholder: 'Bratislava',
      max: 100,
      showInList: true,
    },
    {
      name: 'country',
      type: 'string',
      label: 'Country',
      defaultValue: 'Slovakia',
      max: 100,
      showInList: false,
    },
    {
      name: 'club',
      type: 'string',
      label: 'Running Club',
      placeholder: 'Bratislava Running Club',
      max: 200,
      showInList: true,
      searchable: true,
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
      sortable: true,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
