import { ModelConfig } from '@/lib/admin/types';
import { Trophy } from 'lucide-react';

export const runResultConfig: ModelConfig = {
  name: 'RunResult',
  namePlural: 'Run Results',
  nameSingular: 'Run Result',
  icon: Trophy,
  description: 'Manage race results',
  primaryField: 'id',

  defaultSort: { field: 'overallPlace', direction: 'asc' },
  searchFields: [],
  perPage: 100,

  fields: [
    {
      name: 'id',
      type: 'number',
      label: 'ID',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: true,
    },
    {
      name: 'registrationId',
      type: 'relation',
      label: 'Registration',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Registration',
        displayField: 'registrationNumber',
        foreignKey: 'registrationId',
        idType: 'number',
      },
    },
    {
      name: 'runId',
      type: 'relation',
      label: 'Run',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'Run',
        displayField: 'name',
        foreignKey: 'runId',
        idType: 'number',
      },
    },
    {
      name: 'categoryId',
      type: 'relation',
      label: 'Category',
      required: true,
      showInList: true,
      sortable: true,
      relation: {
        model: 'RunCategory',
        displayField: 'name',
        foreignKey: 'categoryId',
        idType: 'number',
      },
    },
    {
      name: 'runnerId',
      type: 'relation',
      label: 'Runner',
      helpText: 'Denormalized for queries',
      showInList: false,
      relation: {
        model: 'Runner',
        displayField: 'email',
        foreignKey: 'runnerId',
        idType: 'string',
      },
    },
    {
      name: 'overallPlace',
      type: 'number',
      label: 'Overall Place',
      placeholder: '1',
      helpText: 'Overall finishing position',
      showInList: true,
      sortable: true,
    },
    {
      name: 'categoryPlace',
      type: 'number',
      label: 'Category Place',
      placeholder: '1',
      helpText: 'Position within category',
      showInList: true,
      sortable: true,
    },
    {
      name: 'finishTime',
      type: 'number',
      label: 'Finish Time (seconds)',
      placeholder: '3600',
      helpText: 'Finish time in seconds (NULL for DNF/DSQ)',
      showInList: true,
      sortable: true,
    },
    {
      name: 'gunTime',
      type: 'number',
      label: 'Gun Time (seconds)',
      placeholder: '3610',
      helpText: 'Time from gun start (if different from chip time)',
      showInList: false,
    },
    {
      name: 'resultStatus',
      type: 'select',
      label: 'Status',
      required: true,
      defaultValue: 'finished',
      showInList: true,
      sortable: true,
      options: [
        { value: 'finished', label: 'Finished' },
        { value: 'dnf', label: 'DNF (Did Not Finish)' },
        { value: 'dsq', label: 'DSQ (Disqualified)' },
        { value: 'dns', label: 'DNS (Did Not Start)' },
      ],
    },
    {
      name: 'pace',
      type: 'number',
      label: 'Pace (min/km)',
      placeholder: '5.5',
      helpText: 'Calculated pace per kilometer',
      showInList: false,
    },
    {
      name: 'importedAt',
      type: 'date',
      label: 'Imported At',
      helpText: 'When result was imported',
      showInList: false,
    },
    {
      name: 'importSource',
      type: 'select',
      label: 'Import Source',
      showInList: false,
      options: [
        { value: 'csv_import', label: 'CSV Import' },
        { value: 'manual_entry', label: 'Manual Entry' },
      ],
    },
    {
      name: 'createdAt',
      type: 'date',
      label: 'Created At',
      readonly: true,
      hideInCreate: true,
      hideInEdit: true,
      showInList: false,
    },
  ],

  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
